IPUMS = ./ipums
# downloaded from ipums
UNBINNED = ${IPUMS}/cps_00006.csv.gz
# generated by bin2cps
BINNED = ${IPUMS}/cps_00006.1962-2017-binned.csv
# generated by mostreported
REPORTED = mrx.csv

.DELETE_ON_ERROR :

FYEAR = 1972
LYEAR = 2016

CREATEOPTS = 
PNGOPTS = --width 852 --height 480
PDFOPTS = --width 7 --height 4

# graphs for our text
GDIR = graphs
GRAPHS = repro ecdf ecdf2 tidistr tincdistrbybracket \
		histo.hhbracket99-both histo.hhbracket99-1972 \
		mostreported

# extra options any of those need
${GDIR}/totalincome.distribution.OPTIONS = --maxhh 10e8
${GDIR}/histo.hhbracket99.OPTIONS = --maxhh 10e8 --bracket HHBRACKET99
${GDIR}/histo.hhbracket99-both.OPTIONS = ${${GDIR}/histo.hhbracket99.OPTIONS} \
		--years ${FYEAR},${LYEAR}
${GDIR}/histo.hhbracket99-1972.OPTIONS = ${${GDIR}/histo.hhbracket99.OPTIONS} --years 1972
# get the years
${GDIR}/mostreported.OPTIONS = --silentshrink --years $(shell Rscript -e 'seq(${FYEAR},${LYEAR},floor((${LYEAR}-${FYEAR})/4))' | sed 's/^[[][^]][]] *//;s/  */,/g')

# for most reported, default height, width isn't that good.  but,
# maybe shouldn't try to fit so much?  maybe create the big one as a
# separate link (for both pdf and png)?

# good for most reported pdf is: --width 18 --height 12
# for png (slightly big):    --width 2852 --height 1480

FTLARGE = images/DPCIA2AUQAEO0lv.jpg
FTSMALL = images/DPCIA2AUQAEO0lv-small.jpg
# chop the FT image
FT_X_LOW = 0
FT_X_HIGH = 675
FT_Y_LOW = 430
FT_Y_HIGH = 770
FT_X_WIDTH = $(shell expr ${FT_X_HIGH} - ${FT_X_LOW})
FT_Y_HEIGHT = $(shell expr ${FT_Y_HIGH} - ${FT_Y_LOW})


GRAPHSPDF = $(addprefix ${GDIR}/,$(GRAPHS:=.pdf))
GRAPHSPNG = $(addprefix ${GDIR}/,$(GRAPHS:=.png))

GRAPHSALL = ${GRAPHSPDF} ${GRAPHSPNG}

all: ${GRAPHSPDF} ${GRAPHSPNG} ${FTSMALL} ${REPORTED}

${GRAPHSPDF}: Makefile ${BINNED}
	./bin/create.$(subst ${GDIR}/,,$(subst .pdf,,$@)) ${$(subst .pdf,.OPTIONS,$@)} \
				${CREATEOPTS} ${PDFOPTS} --gfile $@ --graphics pdf

${GRAPHSPNG}: Makefile ${BINNED}
	./bin/create.$(subst ${GDIR}/,,$(subst .png,,$@)) ${$(subst .png,.OPTIONS,$@)} \
				${CREATEOPTS} ${PNGOPTS} --gfile $@ --graphics png

${FTSMALL}: ${FTLARGE}
	convert -crop ${FT_X_WIDTH}x${FT_Y_HEIGHT}+${FT_X_LOW}+${FT_Y_LOW} $< $@

${REPORTED}: ${UNBINNED}
	zcat ${UNBINNED} | ./bin/reported > $@

# convenience targets
fyear:
	@echo ${FYEAR}
lyear:
	@echo ${LYEAR}
years:
	@echo "${FYEAR},${LYEAR}"
binned:
	@echo ${BINNED}
reported:
	@echo ${REPORTED}

clean:
	@echo run \"make realclean\" to remove $(BINNED)
	@rm -f ${GRAPHSALL} ${FTSMALL}
realclean:
	rm $(BINNED)
