IPUMS = ./ipums
# downloaded from ipums
UNBINNED = ${IPUMS}/cps_00006.csv.gz
# generated by bin2cps
BINS = ${IPUMS}/cps_00006.1962-2017-binned.csv

FYEAR = 1972
LYEAR = 2016

CREATEOPTS = --ifile ${BINS}
PNGOPTS = --width 852 --height 480
PDFOPTS = --width 7 --height 4

# graphs for our text
GRAPHS = repro ecdf ecdf2 tidistr tincdistrbybracket \
		histo.hhbracket99-both histo.hhbracket99-1972

# extra options any of those need
totalincome.distribution.OPTIONS = --maxhh 10e8
histo.hhbracket99.OPTIONS = --maxhh 10e8 --bracket HHBRACKET99
histo.hhbracket99-both.OPTIONS = ${histo.hhbracket99.OPTIONS} \
		--years ${FYEAR},${LYEAR}
histo.hhbracket99-1972.OPTIONS = ${histo.hhbracket99.OPTIONS} --years 1972


GRAPHSPDF = $(GRAPHS:=.pdf)
GRAPHSPNG = $(GRAPHS:=.png)

GRAPHSALL = ${GRAPHSPDF} ${GRAPHSPNG}

all: ${GRAPHSPDF} ${GRAPHSPNG}

${GRAPHSPDF}: Makefile ${BINS}
	./create.$(subst .pdf,,$@) ${$(subst .pdf,.OPTIONS,$@)} \
				${CREATEOPTS} ${PDFOPTS} --gfile $@ --graphics pdf

${GRAPHSPNG}: Makefile ${BINS}
	./create.$(subst .png,,$@) ${$(subst .png,.OPTIONS,$@)} \
				${CREATEOPTS} ${PNGOPTS} --gfile $@ --graphics png

# convenience targets
fyear:
	@echo ${FYEAR}
lyear:
	@echo ${LYEAR}
years:
	@echo "${FYEAR},${LYEAR}"
bins:
	@echo ${BINS}

clean:
	@echo run \"make realclean\" to remove $(BINS)
	@rm -f ${GRAPHSALL}
realclean:
	rm $(BINS)
