IPUMS = ./ipums
# downloaded from ipums
UNBINNED = ${IPUMS}/cps_00006.csv.gz
# generated by bin2cps
BINS = ${IPUMS}/cps_00006.1962-2017-binned.csv

# graphs for our text
GRAPHS = replot ecdf

GRAPHSPDF = $(GRAPHS:=.pdf)
GRAPHSPNG = $(GRAPHS:=.png)

all: ${GRAPHSPDF} ${GRAPHSPNG}

${GRAPHSPDF}: Makefile ${BINS}
	./create.$(subst .pdf,,$@) --ifile ${BINS} --gfile $@ --graphics pdf

${GRAPHSPNG}: Makefile ${BINS}
	./create.$(subst .png,,$@) --ifile ${BINS} --gfile $@ --graphics png

clean:
	@echo run \"make realclean\" to remove $(BINS)
realclean:
	rm $(BINS)
